import ClientLayout from "./clientlayout";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
